[workspace]
members = [
    "bench/minify-js",
    "cli",
    "rust",
]

[profile.release]
lto = true
strip = true
codegen-units = 1
opt-level = 3

[profile.release.package."*"]
codegen-units = 1
opt-level = 3
