[package]
authors = ["Wilson Lin <code@wilsonl.in>"]
description = "Extremely fast JS minifier"
edition = "2021"
name = "minify-js-cli"
publish = false
version = "0.5.4"

[dependencies]
minify-js = { path = "../rust" }
structopt = "0.3"
